apiVersion: apps/v1
kind: Deployment

metadata:
  name: frontend-deployment
  namespace: erp

spec:

  replicas: 2

  selector:
    matchLabels:
      app: frontend

  template:

    metadata:
      labels:
        app: frontend

    spec:

      containers:

        - name: frontend

          image: kongtheara/frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NUXT_API_BASE_INTERNAL
              value: "http://backend-service:8000"
            - name: BASE_URL
              value: "http://127.0.0.1:8000"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3000

            initialDelaySeconds: 10
            periodSeconds: 10