name: deployment

on:
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:

  backend:
    name: Backend
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          cd back-end
          pip install -r requirements.txt

      - name: Run tests
        run: |
          cd back-end
          pytest

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'push'
        working-directory: backend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/erp-backend:${{ github.sha }} \
            .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/erp-backend:${{ github.sha }}
  
  frontend:
    name: Frontend
    run-on: ubuntu:latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: front-end/package-lock.json
      - name: Install dependency
        working-directory: front-end
        run: |
          npm ci
      
      - name: Build Nuxt
        working-directory: front-end
        run: |
          npm run build

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        if: github.event_name == 'push'
        working-directory: frontend
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/erp-frontend:${{ github.sha }} \
            .

      - name: Push Docker image
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.DOCKERHUB_USERNAME }}/erp-frontend:${{ github.sha }}

